language: node_js
node_js:
  - 8.3.0

cache:
  directories:
    - ~/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn add -g firebase-tools
  - yarn install --frozen-lockfile

before_script:
  - yarn run staging:build
  - yarn ci:start-app-for-test &
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3

script: 'yarn lint && yarn run ci:test'

after_success:
  - firebase use staging --token $FIREBASE_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN
