language: node_js
node_js:
  - 8.3.0

cache:
  directories:
    - ~/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

before_script:
  - NODE_ENV=test yarn run client-build
  - NODE_ENV=test yarn ci:start-app-for-test &
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3

script: 'yarn lint && yarn run ci:test'

env:
  test:
    - secure: JP9ofL3KpCiBOKE9GxyD8zos0QfoWd5ShsU6uK0rmYxVGgpgTuz/KuknTs0TpfM6Ewq6rp+S9Hcq/34H1W51aVIOnN8MzkM2eh0CinwG/cdtQ44LLdeAtraTXAnIYy9KHNFZXVgOt+LyDOlIrp2H6Z7pFS1UJDO8IWFDROcMuqyjbTrxR6nGxa+eBufHV2OwbViLWPaceRNLF0zALX6Ayr5fCpC2yphXF+cBlufxglBEipB+aVlslg7ZZ1obImuYdvMGTXDO5MawKZXavVhQNwiyxe6JkESr1i1wlSLYnFQhScpTKZYcf8HzSBDNooCxjvNEvlR5L1WfE9ROi8uJZMQ6GRPgJ1XVzAIDf/Ijt5iaRIa9u54sZlmnJkSKGTsoahwVX1HLDXMmU3/aGGs4pNV9r1EHAgktTwMvsxWKFDCWKE4n9NVvL6qj95RqCt0z5Aq7sftCtYKRiztcx1A1v+W3qpkUC1KI1lgI5DONOdTxtDrSl+Ak/F272+AOzNm6fa4lppNMym1h0DWSMI45lIrZqm/Tho8e4jrANLKFZ52LyA3gUewN38Q52aQhp1nJFPKAutJo9MeI5esga0EaSSNzzvtr3EZ4Ro3+tm0yQxRSLrqWMns2xaJbQuI+YxMsLlry+Nq9MuNNoAzMC7xNUCiUHo7GERE2FqdLl7nGwKE=
    - secure: QBpW8SByI/4LYWYL6Xj+wAuKk9LijSQWq/nP045h+hBx/P+FsqlwzrOLzQ8nPiSCTaxF3l1u7v6R+XAb77oyFgFM0I2FA9V6w7xmrp6qItox/mHPP/iDKVP78a82tqheRAc9GHUNZwZfm5rDOUJcgF1T0NNt0spOjLIofhAtqotYymqGMJtHyudtQ19mFXWImV4ZSUq17mBbfQymq1x9n7r56jncsMJx763pkJWbo6M4QdeNJwmarGk/phULMt7XG6YWrhOGeEMdhVXXkecRYTmr+P/ATDEBJUW3NZey++8OxT3ABtedF5VHYL2u6g7XQfoz+QWdLvgQBe+q7+inEG8ZkQ9R1+SDOPlxQb6YApAw82juHasJb15soYGokT9+Ga53PZ7A5GtfyIhaP8Gm2fj2ti700eojY4fxVlVIujzCHJ4dPL0bX3YOv1HF2D/nohEIInQrSXA9SOdG6X7veJKzBZKdjrRlAPl++vkrETcC7dTPZ/iS47IWR1FAPXar8011IV5+VTiBhVPzexjpUquI7dyJ+OdsUE6ZjoBl43fVWE3IxVZyr1Nii4WvQ6xAnWR7As8jOMzxZyAjmqnnycf+GnWXyf+vHwEkaSrT+oBATzSOLwsfb61ftIPDJgZdpAtZF3oL2eu7gdj/gAw6cGg3Wk1OoA/rpKulpJGx5og=
    - secure: fDOOCTabMtNPPTuqFDDWkyK52H514Zx0BVp8dr14vYZ8uqNCmErxG7Rcv7nQ7be6W2ES3dpUQAVQ6wwtEiQLtw3Fld7BPWavpDl27C6C93Ebla9hIT7il2U25T6+iDRnXd8j5oGmnkB1qxgg4lXB4Y5HUT5+xTIOGAzfbJX1+vD7YFSdeEatKh67Cf4KCzeWSbfZBqSENLGJ6ySeZT+U2pg8uFO2ZAQdrz6iF1Qu8y3JhUq60e7lln04DfbalEfl2m+tUo+9u3XN3fLRNC+WCIgjgT5IXnZgajxZweW8RHu4e1Y5vKcXa80XzA6atk+77LiDbYilIpRNYEyw16ZyYxadaV+vSsJLKjPqRd0u5BkOlo0t3V42hQGHfZwOf7z/UCvADHrjg2sbuqlroivaMvJyFwZY/F6EQcXX+LczQAQM7JRwQalYkg+wg6MXEJjWrSvg/fC8UBhAHreG36TlDCrCK4mbsTa8m2rVhWlpuSTln+IesHJ2SRnGFAazeHzS1OIrdia/6sCeyzsnDGbvGbkfuNTfUn8dd6hIs62CoGyQKyltP4S8ty9VwU0jOrzKluAS0Va/83nCmAPz6k9vM5hbwquwn9og8QzhoQYz4JT517EFDf2ZIbfCFqFnjg2ozVWaZO+Vhg+u+9yBroZ97IyUZ2gtWwDVlXq6sB3/OtA=
    - secure: uFDelm0P/1kP6Edy4WaL/GEFxonOwFX/bWX4qWMSyX76S+x6tQSERotpAZTrTyICKsjRTS9K4QfcWBb7n2lgyldH36Xba4c8cj7Fj2ZajJ+LIngJyK0MwdTGfwOZ3njHix99YM1ZnJJejYynBejCjabP9weX6farVfmQvGFAdiExFr7LpNr8ZxLiUBiplv1hBw7WxgKBGnCcZobswT1Cc4uR9Xa5pQpbciugabOUxZzYOXCD81BCdgugQ3kgq0Vp5EGQV+l6h1ex5r2UCoPoIgt/0uOC7FV2ejLx/mt6rPW+UXL6zeAWKzgR/52x8xC7zrQyWOVtMpIdiwU2l2Yj/CVxIaPwXdYRi7Lx+aSajKnoX27MRdjazj+oGU7slHZ/6EeneY0GAHrwxJ3d+I1WLZk/cMzlgQgFCXHIfIjWFwNjms4EAB2QJy4k8idSlnzg8Gk0InCdANF6dMnaE6xmbPWOmDHeClDUxhTlMl8GioHTqVedYDl4rUUjAqsBLP7wJipKsUXsVkhMCB4mUlbLDpeO39g271cq+WNaQokUe+sFfBVPrhbyslGq7WD1LWtzwX3XjeWh4JMNEC7JFxX/ymBmpCyVlTdbrskaUgTt0OoFMBji/uAdVz0mjX0n4yyvOExTgi9MrxmlB3oXt8vintP3IlqOd92M+rqQP/tbZBg=
