language: node_js
node_js:
  - 8.3.0

cache:
  directories:
    - ~/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn global add firebase-tools
  - yarn install --frozen-lockfile

before_script:
  - yarn run client:build
  - yarn run client &
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3

script: 'yarn lint && yarn run ci:test'

after_success:
  - firebase use staging --token $FIREBASE_TOKEN
  - firebase deploy --only hosting, firestore:rules -m "PR| $TRAVIS_PULL_REQUEST Build Id| $TRAVIS_BUILD_ID" --token $FIREBASE_TOKEN
