language: node_js
node_js:
  - 8.3.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - NODE_ENV=production yarn run client-build
  - NODE_ENV=production yarn start
script: "yarn lint && yarn run ci:test"
